from django.urls import path

from projects.views import (
    action_complete,
    action_create,
    action_propose_next,
    action_reschedule,
    action_skip,
    analyze_jd,
    application_actions_partial,
    application_drop,
    application_hire,
    application_restore,
    application_resume_request_email,
    application_resume_upload,
    application_resume_use_db,
    application_skip_stage,
    approval_cancel,
    approval_decide,
    approval_queue,
    auto_action_apply,
    auto_action_dismiss,
    draft_consultation,
    draft_consultation_audio,
    draft_convert,
    draft_finalize,
    draft_generate,
    draft_preview,
    draft_review,
    drive_picker,
    interview_create,
    interview_delete,
    interview_result,
    interview_update,
    jd_matching_results,
    jd_results,
    posting_download,
    posting_edit,
    posting_generate,
    posting_site_add,
    posting_site_delete,
    posting_site_update,
    posting_sites,
    project_add_candidate,
    project_applications_partial,
    project_auto_actions,
    project_check_collision,
    project_close,
    project_context,
    project_context_discard,
    project_context_resume,
    project_context_save,
    project_create,
    project_delete,
    project_detail,
    project_list,
    project_reopen,
    project_tab_interviews,
    project_tab_overview,
    project_tab_search,
    project_tab_submissions,
    project_timeline_partial,
    project_update,
    resume_assign_project,
    resume_discard,
    resume_link_candidate,
    resume_process_pending,
    resume_retry,
    resume_unassigned,
    resume_upload,
    resume_upload_status,
    stage_client_submit_single,
    stage_contact_complete,
    stage_interview_complete,
    stage_pre_meeting_record,
    stage_pre_meeting_schedule,
    stage_prep_submission_confirm,
    start_search_session,
    submission_batch_create,
    submission_create,
    submission_delete,
    submission_download,
    submission_draft,
    submission_feedback,
    submission_submit,
    submission_update,
)

app_name = "projects"

urlpatterns = [
    path("", project_list, name="project_list"),
    # P11: Collision check (must be before "new/" to avoid URL conflicts)
    path(
        "new/check-collision/",
        project_check_collision,
        name="project_check_collision",
    ),
    path("new/", project_create, name="project_create"),
    path("<uuid:pk>/", project_detail, name="project_detail"),
    path("<uuid:pk>/edit/", project_update, name="project_update"),
    path("<uuid:pk>/delete/", project_delete, name="project_delete"),
    # Phase 3a: Project lifecycle
    path("<uuid:pk>/close/", project_close, name="project_close"),
    path("<uuid:pk>/reopen/", project_reopen, name="project_reopen"),
    path(
        "<uuid:pk>/applications/",
        project_applications_partial,
        name="project_applications",
    ),
    path(
        "<uuid:pk>/timeline/",
        project_timeline_partial,
        name="project_timeline",
    ),
    # Phase 3b: Application CRUD (stub views)
    path(
        "<uuid:pk>/add_candidate/",
        project_add_candidate,
        name="project_add_candidate",
    ),
    path(
        "applications/<uuid:pk>/drop/",
        application_drop,
        name="application_drop",
    ),
    path(
        "applications/<uuid:pk>/restore/",
        application_restore,
        name="application_restore",
    ),
    path(
        "applications/<uuid:pk>/hire/",
        application_hire,
        name="application_hire",
    ),
    path(
        "applications/<uuid:pk>/skip_stage/",
        application_skip_stage,
        name="application_skip_stage",
    ),
    # Phase C: 접촉 단계 완료
    path(
        "applications/<uuid:pk>/stage/contact/complete/",
        stage_contact_complete,
        name="stage_contact_complete",
    ),
    # Phase C: 면접 단계 완료
    path(
        "applications/<uuid:pk>/stage/interview/complete/",
        stage_interview_complete,
        name="stage_interview_complete",
    ),
    # Phase C: 사전 미팅 단계 — 일정 확정 + 결과 기록
    path(
        "applications/<uuid:pk>/stage/pre_meeting/schedule/",
        stage_pre_meeting_schedule,
        name="stage_pre_meeting_schedule",
    ),
    path(
        "applications/<uuid:pk>/stage/pre_meeting/record/",
        stage_pre_meeting_record,
        name="stage_pre_meeting_record",
    ),
    # Phase C: 제출용 이력서 작성 단계 — 컨설턴트 컨펌
    path(
        "applications/<uuid:pk>/stage/prep_submission/confirm/",
        stage_prep_submission_confirm,
        name="stage_prep_submission_confirm",
    ),
    # Phase C: 이력서 제출 단계 — 개별 경로
    path(
        "applications/<uuid:pk>/stage/client_submit/single/",
        stage_client_submit_single,
        name="stage_client_submit_single",
    ),
    # Phase B: 이력서 수집 단계 — 3가지 방법
    path(
        "applications/<uuid:pk>/resume/use_db/",
        application_resume_use_db,
        name="application_resume_use_db",
    ),
    path(
        "applications/<uuid:pk>/resume/request_email/",
        application_resume_request_email,
        name="application_resume_request_email",
    ),
    path(
        "applications/<uuid:pk>/resume/upload/",
        application_resume_upload,
        name="application_resume_upload",
    ),
    # Phase 3b: ActionItem CRUD (stub views)
    path(
        "applications/<uuid:pk>/actions/",
        application_actions_partial,
        name="application_actions",
    ),
    path(
        "applications/<uuid:pk>/actions/new/",
        action_create,
        name="action_create",
    ),
    path(
        "actions/<uuid:pk>/complete/",
        action_complete,
        name="action_complete",
    ),
    path(
        "actions/<uuid:pk>/skip/",
        action_skip,
        name="action_skip",
    ),
    path(
        "actions/<uuid:pk>/reschedule/",
        action_reschedule,
        name="action_reschedule",
    ),
    path(
        "actions/<uuid:pk>/propose_next/",
        action_propose_next,
        name="action_propose_next",
    ),
    # P03a: JD 분석
    path("<uuid:pk>/analyze-jd/", analyze_jd, name="analyze_jd"),
    path("<uuid:pk>/jd-results/", jd_results, name="jd_results"),
    path("<uuid:pk>/drive-picker/", drive_picker, name="drive_picker"),
    path(
        "<uuid:pk>/start-search/",
        start_search_session,
        name="start_search_session",
    ),
    path("<uuid:pk>/matching/", jd_matching_results, name="jd_matching_results"),
    # P05: 탭 URL
    path(
        "<uuid:pk>/tab/overview/",
        project_tab_overview,
        name="project_tab_overview",
    ),
    path(
        "<uuid:pk>/tab/search/",
        project_tab_search,
        name="project_tab_search",
    ),
    path(
        "<uuid:pk>/tab/submissions/",
        project_tab_submissions,
        name="project_tab_submissions",
    ),
    path(
        "<uuid:pk>/tab/interviews/",
        project_tab_interviews,
        name="project_tab_interviews",
    ),
    # P07: Submission 관리
    path(
        "<uuid:pk>/submissions/new/",
        submission_create,
        name="submission_create",
    ),
    path(
        "<uuid:pk>/submissions/batch/",
        submission_batch_create,
        name="submission_batch_create",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/edit/",
        submission_update,
        name="submission_update",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/delete/",
        submission_delete,
        name="submission_delete",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/submit/",
        submission_submit,
        name="submission_submit",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/feedback/",
        submission_feedback,
        name="submission_feedback",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/download/",
        submission_download,
        name="submission_download",
    ),
    # P08: Draft 파이프라인
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/",
        submission_draft,
        name="submission_draft",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/generate/",
        draft_generate,
        name="draft_generate",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/consultation/",
        draft_consultation,
        name="draft_consultation",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/consultation/audio/",
        draft_consultation_audio,
        name="draft_consultation_audio",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/finalize/",
        draft_finalize,
        name="draft_finalize",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/review/",
        draft_review,
        name="draft_review",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/convert/",
        draft_convert,
        name="draft_convert",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/preview/",
        draft_preview,
        name="draft_preview",
    ),
    # P09: Interview 관리
    path(
        "<uuid:pk>/interviews/new/",
        interview_create,
        name="interview_create",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/edit/",
        interview_update,
        name="interview_update",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/delete/",
        interview_delete,
        name="interview_delete",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/result/",
        interview_result,
        name="interview_result",
    ),
    # P10: Posting 관리
    path(
        "<uuid:pk>/posting/generate/",
        posting_generate,
        name="posting_generate",
    ),
    path(
        "<uuid:pk>/posting/edit/",
        posting_edit,
        name="posting_edit",
    ),
    path(
        "<uuid:pk>/posting/download/",
        posting_download,
        name="posting_download",
    ),
    path(
        "<uuid:pk>/posting/sites/",
        posting_sites,
        name="posting_sites",
    ),
    path(
        "<uuid:pk>/posting/sites/new/",
        posting_site_add,
        name="posting_site_add",
    ),
    path(
        "<uuid:pk>/posting/sites/<uuid:site_pk>/edit/",
        posting_site_update,
        name="posting_site_update",
    ),
    path(
        "<uuid:pk>/posting/sites/<uuid:site_pk>/delete/",
        posting_site_delete,
        name="posting_site_delete",
    ),
    # P11: Approval workflow
    path(
        "<uuid:pk>/approval/cancel/",
        approval_cancel,
        name="approval_cancel",
    ),
    path(
        "approvals/",
        approval_queue,
        name="approval_queue",
    ),
    path(
        "approvals/<uuid:appr_pk>/decide/",
        approval_decide,
        name="approval_decide",
    ),
    # P16: Work Continuity
    path(
        "<uuid:pk>/context/",
        project_context,
        name="project_context",
    ),
    path(
        "<uuid:pk>/context/save/",
        project_context_save,
        name="project_context_save",
    ),
    path(
        "<uuid:pk>/context/resume/",
        project_context_resume,
        name="project_context_resume",
    ),
    path(
        "<uuid:pk>/context/discard/",
        project_context_discard,
        name="project_context_discard",
    ),
    path(
        "<uuid:pk>/auto-actions/",
        project_auto_actions,
        name="project_auto_actions",
    ),
    path(
        "<uuid:pk>/auto-actions/<uuid:action_pk>/apply/",
        auto_action_apply,
        name="auto_action_apply",
    ),
    path(
        "<uuid:pk>/auto-actions/<uuid:action_pk>/dismiss/",
        auto_action_dismiss,
        name="auto_action_dismiss",
    ),
    # P18: Resume upload (project-scoped)
    path(
        "<uuid:pk>/resumes/upload/",
        resume_upload,
        name="resume_upload",
    ),
    path(
        "<uuid:pk>/resumes/process/",
        resume_process_pending,
        name="resume_process_pending",
    ),
    path(
        "<uuid:pk>/resumes/status/",
        resume_upload_status,
        name="resume_upload_status",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/link/",
        resume_link_candidate,
        name="resume_link_candidate",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/discard/",
        resume_discard,
        name="resume_discard",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/retry/",
        resume_retry,
        name="resume_retry",
    ),
    # P18: Unassigned resumes (org-scoped)
    path(
        "resumes/unassigned/",
        resume_unassigned,
        name="resume_unassigned",
    ),
    path(
        "resumes/<uuid:resume_pk>/assign/<uuid:project_pk>/",
        resume_assign_project,
        name="resume_assign_project",
    ),
]
