from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path("", views.project_list, name="project_list"),
    # P11: Collision check (must be before "new/" to avoid URL conflicts)
    path(
        "new/check-collision/",
        views.project_check_collision,
        name="project_check_collision",
    ),
    path("new/", views.project_create, name="project_create"),
    path("<uuid:pk>/", views.project_detail, name="project_detail"),
    path("<uuid:pk>/edit/", views.project_update, name="project_update"),
    path("<uuid:pk>/delete/", views.project_delete, name="project_delete"),
    # Phase 3a: Project lifecycle
    path("<uuid:pk>/close/", views.project_close, name="project_close"),
    path("<uuid:pk>/reopen/", views.project_reopen, name="project_reopen"),
    path(
        "<uuid:pk>/applications/",
        views.project_applications_partial,
        name="project_applications",
    ),
    path(
        "<uuid:pk>/timeline/",
        views.project_timeline_partial,
        name="project_timeline",
    ),
    # Phase 3b: Application CRUD (stub views)
    path(
        "<uuid:pk>/add_candidate/",
        views.project_add_candidate,
        name="project_add_candidate",
    ),
    path(
        "applications/<uuid:pk>/drop/",
        views.application_drop,
        name="application_drop",
    ),
    path(
        "applications/<uuid:pk>/restore/",
        views.application_restore,
        name="application_restore",
    ),
    path(
        "applications/<uuid:pk>/hire/",
        views.application_hire,
        name="application_hire",
    ),
    path(
        "applications/<uuid:pk>/skip_stage/",
        views.application_skip_stage,
        name="application_skip_stage",
    ),
    # Phase C: 접촉 단계 완료
    path(
        "applications/<uuid:pk>/stage/contact/complete/",
        views.stage_contact_complete,
        name="stage_contact_complete",
    ),
    # Phase C: 사전 미팅 단계 — 일정 확정 + 결과 기록
    path(
        "applications/<uuid:pk>/stage/pre_meeting/schedule/",
        views.stage_pre_meeting_schedule,
        name="stage_pre_meeting_schedule",
    ),
    path(
        "applications/<uuid:pk>/stage/pre_meeting/record/",
        views.stage_pre_meeting_record,
        name="stage_pre_meeting_record",
    ),
    # Phase C: 제출용 이력서 작성 단계 — 컨설턴트 컨펌
    path(
        "applications/<uuid:pk>/stage/prep_submission/confirm/",
        views.stage_prep_submission_confirm,
        name="stage_prep_submission_confirm",
    ),
    # Phase C: 이력서 제출 단계 — 개별 경로
    path(
        "applications/<uuid:pk>/stage/client_submit/single/",
        views.stage_client_submit_single,
        name="stage_client_submit_single",
    ),
    # Phase B: 이력서 수집 단계 — 3가지 방법
    path(
        "applications/<uuid:pk>/resume/use_db/",
        views.application_resume_use_db,
        name="application_resume_use_db",
    ),
    path(
        "applications/<uuid:pk>/resume/request_email/",
        views.application_resume_request_email,
        name="application_resume_request_email",
    ),
    path(
        "applications/<uuid:pk>/resume/upload/",
        views.application_resume_upload,
        name="application_resume_upload",
    ),
    # Phase 3b: ActionItem CRUD (stub views)
    path(
        "applications/<uuid:pk>/actions/",
        views.application_actions_partial,
        name="application_actions",
    ),
    path(
        "applications/<uuid:pk>/actions/new/",
        views.action_create,
        name="action_create",
    ),
    path(
        "actions/<uuid:pk>/complete/",
        views.action_complete,
        name="action_complete",
    ),
    path(
        "actions/<uuid:pk>/skip/",
        views.action_skip,
        name="action_skip",
    ),
    path(
        "actions/<uuid:pk>/reschedule/",
        views.action_reschedule,
        name="action_reschedule",
    ),
    path(
        "actions/<uuid:pk>/propose_next/",
        views.action_propose_next,
        name="action_propose_next",
    ),
    # P03a: JD 분석
    path("<uuid:pk>/analyze-jd/", views.analyze_jd, name="analyze_jd"),
    path("<uuid:pk>/jd-results/", views.jd_results, name="jd_results"),
    path("<uuid:pk>/drive-picker/", views.drive_picker, name="drive_picker"),
    path(
        "<uuid:pk>/start-search/",
        views.start_search_session,
        name="start_search_session",
    ),
    path("<uuid:pk>/matching/", views.jd_matching_results, name="jd_matching_results"),
    # P05: 탭 URL
    path(
        "<uuid:pk>/tab/overview/",
        views.project_tab_overview,
        name="project_tab_overview",
    ),
    path(
        "<uuid:pk>/tab/search/",
        views.project_tab_search,
        name="project_tab_search",
    ),
    path(
        "<uuid:pk>/tab/submissions/",
        views.project_tab_submissions,
        name="project_tab_submissions",
    ),
    path(
        "<uuid:pk>/tab/interviews/",
        views.project_tab_interviews,
        name="project_tab_interviews",
    ),
    # P07: Submission 관리
    path(
        "<uuid:pk>/submissions/new/",
        views.submission_create,
        name="submission_create",
    ),
    path(
        "<uuid:pk>/submissions/batch/",
        views.submission_batch_create,
        name="submission_batch_create",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/edit/",
        views.submission_update,
        name="submission_update",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/delete/",
        views.submission_delete,
        name="submission_delete",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/submit/",
        views.submission_submit,
        name="submission_submit",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/feedback/",
        views.submission_feedback,
        name="submission_feedback",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/download/",
        views.submission_download,
        name="submission_download",
    ),
    # P08: Draft 파이프라인
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/",
        views.submission_draft,
        name="submission_draft",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/generate/",
        views.draft_generate,
        name="draft_generate",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/consultation/",
        views.draft_consultation,
        name="draft_consultation",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/consultation/audio/",
        views.draft_consultation_audio,
        name="draft_consultation_audio",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/finalize/",
        views.draft_finalize,
        name="draft_finalize",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/review/",
        views.draft_review,
        name="draft_review",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/convert/",
        views.draft_convert,
        name="draft_convert",
    ),
    path(
        "<uuid:pk>/submissions/<uuid:sub_pk>/draft/preview/",
        views.draft_preview,
        name="draft_preview",
    ),
    # P09: Interview 관리
    path(
        "<uuid:pk>/interviews/new/",
        views.interview_create,
        name="interview_create",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/edit/",
        views.interview_update,
        name="interview_update",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/delete/",
        views.interview_delete,
        name="interview_delete",
    ),
    path(
        "<uuid:pk>/interviews/<uuid:interview_pk>/result/",
        views.interview_result,
        name="interview_result",
    ),
    # P10: Posting 관리
    path(
        "<uuid:pk>/posting/generate/",
        views.posting_generate,
        name="posting_generate",
    ),
    path(
        "<uuid:pk>/posting/edit/",
        views.posting_edit,
        name="posting_edit",
    ),
    path(
        "<uuid:pk>/posting/download/",
        views.posting_download,
        name="posting_download",
    ),
    path(
        "<uuid:pk>/posting/sites/",
        views.posting_sites,
        name="posting_sites",
    ),
    path(
        "<uuid:pk>/posting/sites/new/",
        views.posting_site_add,
        name="posting_site_add",
    ),
    path(
        "<uuid:pk>/posting/sites/<uuid:site_pk>/edit/",
        views.posting_site_update,
        name="posting_site_update",
    ),
    path(
        "<uuid:pk>/posting/sites/<uuid:site_pk>/delete/",
        views.posting_site_delete,
        name="posting_site_delete",
    ),
    # P11: Approval workflow
    path(
        "<uuid:pk>/approval/cancel/",
        views.approval_cancel,
        name="approval_cancel",
    ),
    path(
        "approvals/",
        views.approval_queue,
        name="approval_queue",
    ),
    path(
        "approvals/<uuid:appr_pk>/decide/",
        views.approval_decide,
        name="approval_decide",
    ),
    # P16: Work Continuity
    path(
        "<uuid:pk>/context/",
        views.project_context,
        name="project_context",
    ),
    path(
        "<uuid:pk>/context/save/",
        views.project_context_save,
        name="project_context_save",
    ),
    path(
        "<uuid:pk>/context/resume/",
        views.project_context_resume,
        name="project_context_resume",
    ),
    path(
        "<uuid:pk>/context/discard/",
        views.project_context_discard,
        name="project_context_discard",
    ),
    path(
        "<uuid:pk>/auto-actions/",
        views.project_auto_actions,
        name="project_auto_actions",
    ),
    path(
        "<uuid:pk>/auto-actions/<uuid:action_pk>/apply/",
        views.auto_action_apply,
        name="auto_action_apply",
    ),
    path(
        "<uuid:pk>/auto-actions/<uuid:action_pk>/dismiss/",
        views.auto_action_dismiss,
        name="auto_action_dismiss",
    ),
    # P18: Resume upload (project-scoped)
    path(
        "<uuid:pk>/resumes/upload/",
        views.resume_upload,
        name="resume_upload",
    ),
    path(
        "<uuid:pk>/resumes/process/",
        views.resume_process_pending,
        name="resume_process_pending",
    ),
    path(
        "<uuid:pk>/resumes/status/",
        views.resume_upload_status,
        name="resume_upload_status",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/link/",
        views.resume_link_candidate,
        name="resume_link_candidate",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/discard/",
        views.resume_discard,
        name="resume_discard",
    ),
    path(
        "<uuid:pk>/resumes/<uuid:resume_pk>/retry/",
        views.resume_retry,
        name="resume_retry",
    ),
    # P18: Unassigned resumes (org-scoped)
    path(
        "resumes/unassigned/",
        views.resume_unassigned,
        name="resume_unassigned",
    ),
    path(
        "resumes/<uuid:resume_pk>/assign/<uuid:project_pk>/",
        views.resume_assign_project,
        name="resume_assign_project",
    ),
]
