# Generated by Django 5.2.12 on 2026-03-28 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="business_urgency_score",
            field=models.FloatField(
                blank=True, help_text="업무 긴급도 0-100", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="closeness_score",
            field=models.FloatField(blank=True, help_text="친밀도 0-100", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="relationship_score",
            field=models.FloatField(
                blank=True, help_text="0-100 가중평균 점수", null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="relationship_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gold", "Gold Star"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("red", "Red"),
                    ("gray", "Gray"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="score_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "직접 입력"), ("ai_extracted", "AI 추출")],
                        default="manual",
                        max_length=15,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="contacts.contact",
                    ),
                ),
                (
                    "fc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.interaction",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["is_completed", "due_date", "-created_at"],
            },
        ),
    ]
