# Generated by Django 5.2.12 on 2026-03-29 16:03

from django.db import migrations, models


def migrate_is_completed_to_status(apps, schema_editor):
    """Migrate is_completed boolean to status CharField.
    is_completed=True  → status='done'
    is_completed=False → status='pending'
    """
    Task = apps.get_model("contacts", "Task")
    Task.objects.filter(is_completed=True).update(status="done")
    Task.objects.filter(is_completed=False).update(status="pending")


def migrate_status_to_is_completed(apps, schema_editor):
    """Reverse: migrate status back to is_completed boolean.
    status='done' → is_completed=True
    all others    → is_completed=False
    """
    Task = apps.get_model("contacts", "Task")
    Task.objects.filter(status="done").update(is_completed=True)
    Task.objects.exclude(status="done").update(is_completed=False)


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_migrate_fk_to_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "할 일"), ("waiting", "대기"), ("done", "완료")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            migrate_is_completed_to_status,
            migrate_status_to_is_completed,
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "due_date", "-created_at"]},
        ),
    ]
