# Generated by Django 5.2.12 on 2026-04-14 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0008_notificationpreference"),
        ("candidates", "0022_candidate_consent_status_and_more"),
        ("clients", "0002_p12_reference_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label_ko", models.CharField(max_length=100)),
                ("phase", models.CharField(blank=True, default="", max_length=20)),
                (
                    "default_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_person", "대면"),
                            ("video", "화상"),
                            ("phone", "전화"),
                            ("kakao", "카톡"),
                            ("sms", "문자"),
                            ("email", "이메일"),
                            ("linkedin", "LinkedIn"),
                            ("other", "기타"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "output_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "없음"),
                            ("submission", "서류 패키지"),
                            ("interview", "면접"),
                            ("meeting", "사전미팅"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_protected", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("suggests_next", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("hired_at", models.DateTimeField(blank=True, null=True)),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfit", "부적합"),
                            ("candidate_declined", "후보자 거절/포기"),
                            ("client_rejected", "클라이언트 탈락"),
                            ("other", "기타"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("drop_note", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_person", "대면"),
                            ("video", "화상"),
                            ("phone", "전화"),
                            ("kakao", "카톡"),
                            ("sms", "문자"),
                            ("email", "이메일"),
                            ("linkedin", "LinkedIn"),
                            ("other", "기타"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("done", "완료"),
                            ("skipped", "건너뜀"),
                            ("cancelled", "취소"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="projects.actionitem",
                    ),
                ),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="projects.actiontype",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="projects.application",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round", models.PositiveSmallIntegerField()),
                ("scheduled_at", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("대면", "대면"), ("화상", "화상"), ("전화", "전화")],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=500)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("합격", "합격"),
                            ("보류", "보류"),
                            ("탈락", "탈락"),
                        ],
                        default="대기",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "action_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="projects.actionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["round"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audio_file", models.FileField(upload_to="meetings/audio/")),
                ("transcript", models.TextField(blank=True)),
                ("analysis_json", models.JSONField(blank=True, default=dict)),
                ("edited_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "업로드됨"),
                            ("transcribing", "전사 중"),
                            ("analyzing", "분석 중"),
                            ("ready", "분석 완료"),
                            ("applied", "반영 완료"),
                            ("failed", "실패"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_record",
                        to="projects.actionitem",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_meeting_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meeting_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS/뉴스"),
                            ("youtube", "YouTube"),
                            ("blog", "블로그"),
                        ],
                        default="rss",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hiring", "채용"),
                            ("hr", "인사"),
                            ("industry", "업계동향"),
                            ("economy", "경제/실업"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_sources",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("raw_content", models.TextField(blank=True)),
                ("url", models.URLField(unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hiring", "채용"),
                            ("hr", "인사"),
                            ("industry", "업계동향"),
                            ("economy", "경제/실업"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="projects.newssource",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("approval_request", "승인 요청"),
                            ("auto_generated", "자동 생성"),
                            ("reminder", "리마인더"),
                            ("news", "뉴스"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("action_url", models.URLField(blank=True)),
                ("telegram_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("sent", "전송됨"),
                            ("read", "읽음"),
                            ("acted", "처리됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("callback_data", models.JSONField(blank=True, default=dict)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("jd_text", models.TextField(blank=True)),
                ("jd_file", models.FileField(blank=True, upload_to="projects/jd/")),
                (
                    "jd_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upload", "파일 업로드"),
                            ("drive", "Google Drive"),
                            ("text", "텍스트 입력"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jd_drive_file_id", models.CharField(blank=True, max_length=255)),
                ("jd_raw_text", models.TextField(blank=True)),
                ("jd_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "phase",
                    models.CharField(
                        choices=[("searching", "서칭"), ("screening", "심사")],
                        db_index=True,
                        default="searching",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "진행중"), ("closed", "종료")],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("success", "성공"), ("fail", "실패")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("posting_text", models.TextField(blank=True)),
                ("posting_file_name", models.CharField(blank=True, max_length=300)),
                (
                    "assigned_consultants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostingSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("jobkorea", "잡코리아"),
                            ("saramin", "사람인"),
                            ("incruit", "인크루트"),
                            ("linkedin", "LinkedIn"),
                            ("wanted", "원티드"),
                            ("catch", "캐치"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("applicant_count", models.PositiveIntegerField(default=0)),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_sites",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticleRelevance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField()),
                ("matched_terms", models.JSONField(blank=True, default=list)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relevances",
                        to="projects.newsarticle",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_relevances",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="AutoAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trigger_event", models.CharField(max_length=100)),
                ("action_type", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("applied", "적용됨"),
                            ("dismissed", "무시됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_auto_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dismissed_auto_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_actions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conflict_score", models.FloatField(default=0.0)),
                (
                    "conflict_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("높은중복", "높은 중복 가능성"),
                            ("참고정보", "참고 정보"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기", "대기"),
                            ("승인", "승인"),
                            ("합류", "합류"),
                            ("반려", "반려"),
                        ],
                        default="대기",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("admin_response", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conflict_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflict_approvals",
                        to="projects.project",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_step", models.CharField(blank=True, max_length=100)),
                ("pending_action", models.CharField(blank=True, max_length=100)),
                ("draft_data", models.JSONField(blank=True, default=dict)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="resumes/uploads/")),
                ("file_name", models.CharField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word (DOCX)"),
                            ("doc", "Word (DOC)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "수동 업로드"), ("email", "이메일")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("extracting", "추출중"),
                            ("extracted", "추출완료"),
                            ("linked", "후보자 연결됨"),
                            ("duplicate", "중복"),
                            ("failed", "실패"),
                            ("discarded", "폐기"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extraction_result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("email_subject", models.CharField(blank=True, max_length=500)),
                ("email_from", models.EmailField(blank=True, max_length=254)),
                ("email_message_id", models.CharField(blank=True, max_length=255)),
                ("email_attachment_id", models.CharField(blank=True, max_length=255)),
                ("upload_batch", models.UUIDField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_uploads",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_uploads",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_uploads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("xd_ko", "엑스다임 국문"),
                            ("xd_ko_en", "엑스다임 국영문"),
                            ("xd_en", "엑스다임 영문"),
                            ("custom", "고객사 커스텀"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(blank=True, upload_to="submissions/"),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("client_feedback", models.TextField(blank=True)),
                ("client_feedback_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "action_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="projects.actionitem",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("draft_generated", "초안 생성됨"),
                            ("consultation_added", "상담 입력됨"),
                            ("finalized", "AI 정리 완료"),
                            ("reviewed", "검토 완료"),
                            ("converted", "변환 완료"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("auto_draft_json", models.JSONField(blank=True, default=dict)),
                ("auto_corrections", models.JSONField(blank=True, default=list)),
                ("consultation_input", models.TextField(blank=True)),
                (
                    "consultation_audio",
                    models.FileField(blank=True, upload_to="drafts/audio/"),
                ),
                ("consultation_transcript", models.TextField(blank=True)),
                ("consultation_summary", models.JSONField(blank=True, default=dict)),
                ("final_content_json", models.JSONField(blank=True, default=dict)),
                ("masking_config", models.JSONField(blank=True, default=dict)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("word", "Word"), ("pdf", "PDF")],
                        default="word",
                        max_length=10,
                    ),
                ),
                (
                    "output_language",
                    models.CharField(
                        choices=[("ko", "국문"), ("en", "영문"), ("ko_en", "국영문")],
                        default="ko",
                        max_length=10,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, upload_to="drafts/output/"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="projects.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["application", "status"], name="projects_ac_applica_4005de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["assigned_to", "status", "due_at"],
                name="projects_ac_assigne_cc0f92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["action_type", "status"], name="projects_ac_action__27c552_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["application", "status", "-completed_at"],
                name="projects_ac_applica_1716eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["phase", "status"], name="projects_pr_phase_44081c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["deadline"], name="projects_pr_deadlin_bd2912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "status"], name="projects_pr_organiz_8941e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_at__isnull", False), ("status", "open"), _negated=True
                ),
                name="project_open_implies_no_closed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "open"), _negated=True),
                    ("result", ""),
                    _connector="OR",
                ),
                name="project_open_implies_empty_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result", ""), ("status", "closed"), _connector="OR"
                ),
                name="project_result_implies_closed",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingsite",
            constraint=models.UniqueConstraint(
                fields=("project", "site"), name="unique_posting_site_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsarticlerelevance",
            constraint=models.UniqueConstraint(
                fields=("article", "project"), name="unique_article_project_relevance"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["project", "dropped_at", "hired_at"],
                name="projects_ap_project_4822f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate"], name="projects_ap_candida_757d2d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("project", "candidate"),
                name="unique_application_per_project_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcontext",
            constraint=models.UniqueConstraint(
                fields=("project", "consultant"),
                name="unique_context_per_project_consultant",
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeupload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "email")),
                fields=("organization", "email_message_id", "email_attachment_id"),
                name="unique_email_attachment_per_org",
            ),
        ),
    ]
