"""Seed 23 initial ActionType rows.

4 protected: pre_meeting, submit_to_client, interview_round, confirm_hire.
Full suggests_next chain for all 23 types.
"""

from django.db import migrations


ACTION_TYPES = [
    # --- Searching phase (13) ---
    {
        "code": "search_db",
        "label_ko": "DB 후보자 검색",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 10,
        "is_active": True,
        "is_protected": False,
        "description": "내부 DB에서 조건에 맞는 후보자를 검색한다.",
        "suggests_next": ["reach_out"],
    },
    {
        "code": "search_external",
        "label_ko": "외부 소스 탐색",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 20,
        "is_active": True,
        "is_protected": False,
        "description": "LinkedIn, 잡코리아 등 외부 소스에서 후보자를 탐색한다.",
        "suggests_next": ["reach_out"],
    },
    {
        "code": "reach_out",
        "label_ko": "후보자 연락",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 30,
        "is_active": True,
        "is_protected": False,
        "description": "후보자에게 첫 연락을 시도한다.",
        "suggests_next": ["await_reply", "schedule_pre_meet"],
    },
    {
        "code": "re_reach_out",
        "label_ko": "재연락",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 40,
        "is_active": True,
        "is_protected": False,
        "description": "미응답 후보자에게 재연락한다.",
        "suggests_next": ["await_reply", "schedule_pre_meet"],
    },
    {
        "code": "await_reply",
        "label_ko": "답장 대기",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 50,
        "is_active": True,
        "is_protected": False,
        "description": "후보자의 답장을 기다린다.",
        "suggests_next": ["re_reach_out", "schedule_pre_meet"],
    },
    {
        "code": "share_jd",
        "label_ko": "JD 공유",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 60,
        "is_active": True,
        "is_protected": False,
        "description": "후보자에게 채용 공고(JD)를 공유한다.",
        "suggests_next": ["receive_resume", "await_reply"],
    },
    {
        "code": "receive_resume",
        "label_ko": "이력서 수령",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 70,
        "is_active": True,
        "is_protected": False,
        "description": "후보자로부터 이력서를 수령한다.",
        "suggests_next": ["convert_resume"],
    },
    {
        "code": "convert_resume",
        "label_ko": "내부 양식 변환",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 80,
        "is_active": True,
        "is_protected": False,
        "description": "수령한 이력서를 내부 양식으로 변환한다.",
        "suggests_next": ["schedule_pre_meet", "prepare_submission"],
    },
    {
        "code": "schedule_pre_meet",
        "label_ko": "사전미팅 일정 조율",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 90,
        "is_active": True,
        "is_protected": False,
        "description": "후보자와 사전미팅 일정을 조율한다.",
        "suggests_next": ["pre_meeting"],
    },
    {
        "code": "pre_meeting",
        "label_ko": "사전미팅 실시",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "meeting",
        "sort_order": 100,
        "is_active": True,
        "is_protected": True,
        "description": "후보자와 사전미팅을 진행한다. MeetingRecord가 연결된다.",
        "suggests_next": ["prepare_submission", "follow_up"],
    },
    {
        "code": "prepare_submission",
        "label_ko": "제출 이력서 작성",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 110,
        "is_active": True,
        "is_protected": False,
        "description": "클라이언트에 제출할 이력서를 작성한다.",
        "suggests_next": ["submit_to_client"],
    },
    {
        "code": "submit_to_pm",
        "label_ko": "내부 PM 1차 검토",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 120,
        "is_active": True,
        "is_protected": False,
        "description": "내부 PM에게 1차 검토를 요청한다.",
        "suggests_next": ["submit_to_client"],
    },
    {
        "code": "submit_to_client",
        "label_ko": "클라이언트 제출",
        "phase": "searching",
        "default_channel": "",
        "output_kind": "submission",
        "sort_order": 130,
        "is_active": True,
        "is_protected": True,
        "description": "클라이언트에게 추천 서류를 제출한다. Submission이 연결된다. Phase 전환 트리거.",
        "suggests_next": ["await_doc_review"],
    },
    # --- Screening phase (7) ---
    {
        "code": "await_doc_review",
        "label_ko": "서류 심사 대기",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 200,
        "is_active": True,
        "is_protected": False,
        "description": "클라이언트의 서류 심사 결과를 기다린다.",
        "suggests_next": ["receive_doc_feedback"],
    },
    {
        "code": "receive_doc_feedback",
        "label_ko": "서류 피드백 수령",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 210,
        "is_active": True,
        "is_protected": False,
        "description": "클라이언트로부터 서류 심사 피드백을 수령한다.",
        "suggests_next": ["schedule_interview", "follow_up"],
    },
    {
        "code": "schedule_interview",
        "label_ko": "면접 일정 조율",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 220,
        "is_active": True,
        "is_protected": False,
        "description": "후보자와 클라이언트 간 면접 일정을 조율한다.",
        "suggests_next": ["interview_round"],
    },
    {
        "code": "interview_round",
        "label_ko": "면접 실시",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "interview",
        "sort_order": 230,
        "is_active": True,
        "is_protected": True,
        "description": "면접을 실시한다. Interview가 연결된다.",
        "suggests_next": ["await_interview_result", "interview_round"],
    },
    {
        "code": "await_interview_result",
        "label_ko": "면접 결과 대기",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 240,
        "is_active": True,
        "is_protected": False,
        "description": "면접 결과를 기다린다.",
        "suggests_next": ["confirm_hire", "follow_up"],
    },
    {
        "code": "confirm_hire",
        "label_ko": "입사 확정",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 250,
        "is_active": True,
        "is_protected": True,
        "description": "입사를 확정한다. 프로젝트 종료 자동화 트리거.",
        "suggests_next": ["await_onboarding"],
    },
    {
        "code": "await_onboarding",
        "label_ko": "입사일 대기",
        "phase": "screening",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 260,
        "is_active": True,
        "is_protected": False,
        "description": "확정된 후보자의 입사일을 기다린다.",
        "suggests_next": ["follow_up"],
    },
    # --- Universal (3) ---
    {
        "code": "follow_up",
        "label_ko": "팔로업",
        "phase": "",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 900,
        "is_active": True,
        "is_protected": False,
        "description": "후속 연락 또는 확인을 수행한다.",
        "suggests_next": [],
    },
    {
        "code": "escalate_to_boss",
        "label_ko": "사장님 에스컬레이션",
        "phase": "",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 910,
        "is_active": True,
        "is_protected": False,
        "description": "이슈를 사장님(대표)에게 에스컬레이션한다.",
        "suggests_next": ["follow_up"],
    },
    {
        "code": "note",
        "label_ko": "단순 메모",
        "phase": "",
        "default_channel": "",
        "output_kind": "",
        "sort_order": 920,
        "is_active": True,
        "is_protected": False,
        "description": "업무 관련 단순 메모를 남긴다.",
        "suggests_next": [],
    },
]


def forwards(apps, schema_editor):
    ActionType = apps.get_model("projects", "ActionType")
    for data in ACTION_TYPES:
        ActionType.objects.update_or_create(code=data["code"], defaults=data)


def backwards(apps, schema_editor):
    ActionType = apps.get_model("projects", "ActionType")
    codes = [d["code"] for d in ACTION_TYPES]
    ActionType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [("projects", "0001_initial")]
    operations = [migrations.RunPython(forwards, backwards)]
