# Generated by Django 5.2.12 on 2026-04-14 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0022_candidate_consent_status_and_more"),
        ("projects", "0002_seed_action_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hired_at__isnull", False)),
                fields=("project",),
                name="unique_hired_per_project",
            ),
        ),
    ]
