# Generated by Django 5.2.12 on 2026-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_application_unique_hired_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='포지션 연봉 (원)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='수수료율 (%, 예: 20.00)', max_digits=5, null=True),
        ),
    ]
