# Generated by Django 5.2.12 on 2026-04-08 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_p07_submission_template_feedback_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("draft_generated", "초안 생성됨"),
                            ("consultation_added", "상담 입력됨"),
                            ("finalized", "AI 정리 완료"),
                            ("reviewed", "검토 완료"),
                            ("converted", "변환 완료"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("auto_draft_json", models.JSONField(blank=True, default=dict)),
                ("auto_corrections", models.JSONField(blank=True, default=list)),
                ("consultation_input", models.TextField(blank=True)),
                (
                    "consultation_audio",
                    models.FileField(blank=True, upload_to="drafts/audio/"),
                ),
                ("consultation_transcript", models.TextField(blank=True)),
                ("consultation_summary", models.JSONField(blank=True, default=dict)),
                ("final_content_json", models.JSONField(blank=True, default=dict)),
                ("masking_config", models.JSONField(blank=True, default=dict)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("word", "Word"), ("pdf", "PDF")],
                        default="word",
                        max_length=10,
                    ),
                ),
                (
                    "output_language",
                    models.CharField(
                        choices=[("ko", "국문"), ("en", "영문"), ("ko_en", "국영문")],
                        default="ko",
                        max_length=10,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, upload_to="drafts/output/"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="projects.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
