# Generated by Django 5.2.12 on 2026-04-20 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_remove_candidate_owned_by'),
        ('projects', '0005_submission_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resumeupload',
            name='unique_email_attachment_per_org',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_organiz_8941e0_idx',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='resumeupload',
            name='organization',
        ),
        migrations.AddConstraint(
            model_name='resumeupload',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'email')), fields=('email_message_id', 'email_attachment_id'), name='unique_email_attachment'),
        ),
    ]
