# Generated by Django 5.2.12 on 2026-04-08 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_p09_interview_offer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="posting_file_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name="PostingSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("jobkorea", "잡코리아"),
                            ("saramin", "사람인"),
                            ("incruit", "인크루트"),
                            ("linkedin", "LinkedIn"),
                            ("wanted", "원티드"),
                            ("catch", "캐치"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("applicant_count", models.PositiveIntegerField(default=0)),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_sites",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "site"),
                        name="unique_posting_site_per_project",
                    )
                ],
            },
        ),
    ]
