# Generated by Django 5.2.12 on 2026-04-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_p10_posting_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapproval",
            name="conflict_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="projectapproval",
            name="conflict_type",
            field=models.CharField(
                blank=True,
                choices=[("높은중복", "높은 중복 가능성"), ("참고정보", "참고 정보")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectapproval",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals",
                to="projects.project",
            ),
        ),
    ]
