# Generated by Django 5.2.12 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_meetingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
