# Generated by Django 5.2.12 on 2026-04-10 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_news_seen_at'),
        ('projects', '0012_autoaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('rss', 'RSS/뉴스'), ('youtube', 'YouTube'), ('blog', '블로그')], default='rss', max_length=20)),
                ('category', models.CharField(choices=[('hiring', '채용'), ('hr', '인사'), ('industry', '업계동향'), ('economy', '경제/실업')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sources', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('raw_content', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, choices=[('hiring', '채용'), ('hr', '인사'), ('industry', '업계동향'), ('economy', '경제/실업')], max_length=20)),
                ('summary_status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='projects.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleRelevance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevances', to='projects.newsarticle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_relevances', to='projects.project')),
            ],
            options={
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('article', 'project'), name='unique_article_project_relevance')],
            },
        ),
    ]
