# Generated by Django 5.2.12 on 2026-04-10 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailmonitorconfig'),
        ('candidates', '0021_candidate_owned_by'),
        ('projects', '0013_newssource_newsarticle_newsarticlerelevance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='resumes/uploads/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('doc', 'Word (DOC)')], max_length=10)),
                ('source', models.CharField(choices=[('manual', '수동 업로드'), ('email', '이메일')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('pending', '대기'), ('extracting', '추출중'), ('extracted', '추출완료'), ('linked', '후보자 연결됨'), ('duplicate', '중복'), ('failed', '실패'), ('discarded', '폐기')], default='pending', max_length=20)),
                ('extraction_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('email_attachment_id', models.CharField(blank=True, max_length=255)),
                ('upload_batch', models.UUIDField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_uploads', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_uploads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_uploads', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_uploads', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'email')), fields=('organization', 'email_message_id', 'email_attachment_id'), name='unique_email_attachment_per_org')],
            },
        ),
    ]
