# Generated by Django 5.2.12 on 2026-03-29 09:29

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


def deduplicate_fortunate_insights(apps, schema_editor):
    """Remove duplicate (fc, contact) rows before adding unique_together.
    Priority: keep is_dismissed=True row (preserve user intent).
    If tie, keep most recent created_at."""
    FortunateInsight = apps.get_model("intelligence", "FortunateInsight")
    from django.db.models import Count

    dupes = (
        FortunateInsight.objects.values("fc", "contact")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for dupe in dupes:
        rows = FortunateInsight.objects.filter(
            fc=dupe["fc"], contact=dupe["contact"]
        ).order_by("-is_dismissed", "-created_at")
        # Keep first (is_dismissed=True preferred, then newest), delete rest
        keep = rows.first()
        rows.exclude(pk=keep.pk).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_business_urgency_score_and_more'),
        ('intelligence', '0002_analysisjob_fortunateinsight_relationshipanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(deduplicate_fortunate_insights, noop),
        migrations.AlterUniqueTogether(
            name='fortunateinsight',
            unique_together={('fc', 'contact')},
        ),
        migrations.CreateModel(
            name='ContactEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('source_text', models.TextField()),
                ('source_hash', models.CharField(max_length=64)),
                ('model_version', models.CharField(default='gemini-embedding-001', max_length=50)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_count', models.PositiveIntegerField()),
                ('interaction_count', models.PositiveIntegerField()),
                ('embedding_done', models.BooleanField(default=False)),
                ('sentiment_done', models.BooleanField(default=False)),
                ('task_done', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
