"""initial tables

Revision ID: 722606141b25
Revises: 
Create Date: 2026-03-27 04:47:46.717860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722606141b25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kakao_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('ga_name', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.String(length=50), nullable=True),
    sa.Column('push_subscription', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fc_id', sa.String(length=36), nullable=False),
    sa.Column('ceo_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ceo_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_fc_id'), 'contacts', ['fc_id'], unique=False)
    op.create_table('briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('fc_id', sa.String(length=36), nullable=False),
    sa.Column('company_analysis', sa.Text(), nullable=True),
    sa.Column('action_suggestion', sa.Text(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['fc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_contact_id'), 'briefs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_briefs_fc_id'), 'briefs', ['fc_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_a_id', sa.String(length=36), nullable=False),
    sa.Column('contact_b_id', sa.String(length=36), nullable=False),
    sa.Column('fc_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('industry_fit', sa.Float(), nullable=False),
    sa.Column('region_proximity', sa.Float(), nullable=False),
    sa.Column('size_balance', sa.Float(), nullable=False),
    sa.Column('synergy_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_a_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['contact_b_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['fc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_contact_a_id'), 'matches', ['contact_a_id'], unique=False)
    op.create_index(op.f('ix_matches_contact_b_id'), 'matches', ['contact_b_id'], unique=False)
    op.create_index(op.f('ix_matches_fc_id'), 'matches', ['fc_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fc_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('memo_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['fc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_contact_id'), 'meetings', ['contact_id'], unique=False)
    op.create_index(op.f('ix_meetings_fc_id'), 'meetings', ['fc_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fc_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['fc_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_contact_id'), 'interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interactions_fc_id'), 'interactions', ['fc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_fc_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_contact_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_meetings_fc_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_contact_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_matches_fc_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_contact_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_contact_a_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_briefs_fc_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_contact_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_contacts_fc_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
