# Generated by Django 5.2.12 on 2026-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitytier',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='canonical name 외 표기 변형 (한+영 병기, 약어, LLM 비결정 출력 등)'),
        ),
        migrations.AddField(
            model_name='universitytier',
            name='auto_added',
            field=models.BooleanField(default=False, help_text='LLM이 자동 등록한 항목. 검수자 라벨링 후 false 처리.'),
        ),
        migrations.AddField(
            model_name='universitytier',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='검수 대기 (tier 미부여, LLM confidence 낮음, 또는 신규 발견).'),
        ),
        migrations.AlterField(
            model_name='universitytier',
            name='tier',
            field=models.CharField(blank=True, choices=[('SKY', 'SKY'), ('SSG', '서성한'), ('JKOS', '중경외시'), ('KDH', '건동홍숙이'), ('INSEOUL', '인서울'), ('SCIENCE_ELITE', '과기특'), ('REGIONAL', '지방거점'), ('OVERSEAS_TOP', '해외 최상위'), ('OVERSEAS_HIGH', '해외 상위'), ('OVERSEAS_GOOD', '해외 우수')], max_length=20),
        ),
    ]
