# Generated by Django 5.2.12 on 2026-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="preference_tier",
        ),
        migrations.RemoveField(
            model_name="preferredcert",
            name="description",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="employee_count_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="listed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KOSPI", "KOSPI"),
                    ("KOSDAQ", "KOSDAQ"),
                    ("비상장", "비상장"),
                    ("해외상장", "해외상장"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="name_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="preferredcert",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="preferredcert",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="preferredcert",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("상", "상"), ("중", "중"), ("하", "하")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="preferredcert",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="universitytier",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="size_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("대기업", "대기업"),
                    ("중견", "중견"),
                    ("중소", "중소"),
                    ("외국계", "외국계"),
                    ("스타트업", "스타트업"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="preferredcert",
            name="category",
            field=models.CharField(
                choices=[
                    ("회계/재무", "회계/재무"),
                    ("법률", "법률"),
                    ("기술/엔지니어링", "기술/엔지니어링"),
                    ("IT", "IT"),
                    ("의료/제약", "의료/제약"),
                    ("무역/물류", "무역/물류"),
                    ("건설/부동산", "건설/부동산"),
                    ("식품/환경", "식품/환경"),
                    ("어학", "어학"),
                    ("안전/품질", "안전/품질"),
                    ("기타", "기타"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="universitytier",
            name="ranking",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="universitytier",
            name="tier",
            field=models.CharField(
                choices=[
                    ("SKY", "SKY"),
                    ("SSG", "서성한"),
                    ("JKOS", "중경외시"),
                    ("KDH", "건동홍"),
                    ("INSEOUL", "인서울 기타"),
                    ("SCIENCE_ELITE", "이공계 명문"),
                    ("REGIONAL", "지방 거점 국립"),
                    ("OVERSEAS_TOP", "해외 최상위"),
                    ("OVERSEAS_HIGH", "해외 상위"),
                    ("OVERSEAS_GOOD", "해외 우수"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="universitytier",
            unique_together={("name", "country")},
        ),
    ]
