# Generated by Django 5.2.12 on 2026-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_p12_reference_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
