# Generated by Django 5.2.12 on 2026-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_migrate_industry_to_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("바이오/제약", "바이오 / 제약"),
                    ("헬스케어/의료기기", "헬스케어 / 의료기기"),
                    ("IT/SW", "IT / SW"),
                    ("소재/부품", "소재 / 부품"),
                    ("금융/캐피탈", "금융 / 캐피탈"),
                    ("소비재/패션", "소비재 / 패션"),
                    ("환경/유틸리티", "환경 / 유틸리티"),
                    ("모빌리티/제조", "모빌리티 / 제조"),
                    ("미디어/엔터", "미디어 / 엔터"),
                    ("건설/부동산", "건설 / 부동산"),
                    ("기타", "기타"),
                ],
                default="기타",
                max_length=30,
            ),
        ),
    ]
