# Generated by Django 5.2.12 on 2026-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_alter_client_industry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="universitytier",
            options={
                "ordering": [
                    models.OrderBy(models.F("ranking"), nulls_last=True),
                    "tier",
                    "name",
                ]
            },
        ),
        migrations.AlterField(
            model_name="universitytier",
            name="tier",
            field=models.CharField(
                choices=[
                    ("SKY", "SKY"),
                    ("SSG", "서성한"),
                    ("JKOS", "중경외시"),
                    ("KDH", "건동홍숙이"),
                    ("INSEOUL", "인서울"),
                    ("SCIENCE_ELITE", "과기특"),
                    ("REGIONAL", "지방거점"),
                    ("OVERSEAS_TOP", "해외 최상위"),
                    ("OVERSEAS_HIGH", "해외 상위"),
                    ("OVERSEAS_GOOD", "해외 우수"),
                ],
                max_length=20,
            ),
        ),
    ]
