# Generated by Django 5.2.12 on 2026-04-19 17:48

from django.db import migrations, models


UNIVERSITY_DATA = {
    # name -> (university_type, strengths)
    "서울대학교": ("국립", ["전 분야"]),
    "KAIST": ("국립(특수)", ["전기전자", "컴퓨터", "기계"]),
    "연세대학교": ("사립", ["경영", "사회학", "언론"]),
    "고려대학교": ("사립", ["경영", "법학", "AI"]),
    "포항공과대학교": ("사립(특수)", ["화학", "재료", "물리"]),
    "성균관대학교": ("사립", ["반도체", "화학공학"]),
    "한양대학교": ("사립", ["건축", "기계", "전기전자"]),
    "서강대학교": ("사립", ["경영", "철학", "영문"]),
    "중앙대학교": ("사립", ["예술", "경영"]),
    "경희대학교": ("사립", ["한의학", "국제학"]),
    "한국외국어대학교": ("사립", ["외국어", "국제학", "통번역"]),
    "서울시립대학교": ("시립", ["도시공학", "세무"]),
    "건국대학교": ("사립", ["부동산", "경영"]),
    "동국대학교": ("사립", ["경찰", "영화"]),
    "홍익대학교": ("사립", ["미술", "디자인"]),
    "숙명여자대학교": ("사립", ["경영", "미디어"]),
    "이화여자대학교": ("사립", ["여성학", "약학", "교육"]),
    "국민대학교": ("사립", ["자동차", "디자인"]),
    "숭실대학교": ("사립", ["IT", "컴퓨터"]),
    "세종대학교": ("사립", ["호텔관광", "AI"]),
    "UNIST": ("국립(특수)", ["에너지", "재료"]),
    "GIST": ("국립(특수)", ["광학", "전기전자"]),
    "DGIST": ("국립(특수)", ["로봇", "뇌과학"]),
    "부산대학교": ("국립", ["공학", "의학"]),
    "경북대학교": ("국립", ["공학", "의학"]),
    "전남대학교": ("국립", ["의학", "농학"]),
    "전북대학교": ("국립", ["공학", "농학"]),
    "충남대학교": ("국립", ["약학", "공학"]),
    "충북대학교": ("국립", ["법학", "농학"]),
    "강원대학교": ("국립", ["산림", "의학"]),
    "제주대학교": ("국립", ["해양", "관광"]),
    "Harvard University": ("해외", ["경영", "법학", "의학"]),
    "MIT": ("해외", ["공학", "컴퓨터", "자연과학"]),
    "University of Oxford": ("해외", ["인문", "자연과학", "법학"]),
}


def populate(apps, schema_editor):
    UniversityTier = apps.get_model("clients", "UniversityTier")
    for u in UniversityTier.objects.all():
        if u.name in UNIVERSITY_DATA:
            u.university_type, u.strengths = UNIVERSITY_DATA[u.name]
            u.save(update_fields=["university_type", "strengths"])


def rollback(apps, schema_editor):
    UniversityTier = apps.get_model("clients", "UniversityTier")
    UniversityTier.objects.update(university_type="", strengths=[])


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_alter_universitytier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="universitytier",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="universitytier",
            name="university_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("국립", "국립"),
                    ("국립(특수)", "국립(특수)"),
                    ("사립", "사립"),
                    ("사립(특수)", "사립(특수)"),
                    ("시립", "시립"),
                    ("해외", "해외"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(populate, rollback),
    ]
