# Generated by Django 5.2.12 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_university_type_strengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='organization',
        ),
    ]
