# Generated by Django 5.2.12 on 2026-04-20 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kakao_id",
        ),
    ]
