# Generated by Django 5.2.12 on 2026-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_telegrambinding_verified_at_telegramverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_news_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
