# Generated by Django 5.2.12 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, '대기'), (1, '직원'), (2, '사장')], default=0),
        ),
    ]
