# Generated by Django 5.2.12 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_level'),
        ('candidates', '0023_remove_candidate_owned_by'),
        ('clients', '0008_remove_client_organization'),
        ('projects', '0006_remove_resumeupload_unique_email_attachment_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
