# Generated by Django 5.2.12 on 2026-03-28 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='contacts.contact')),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
