# Generated by Django 5.2.12 on 2026-03-30 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_ko", models.CharField(blank=True, max_length=100)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=200)),
                ("birth_year", models.SmallIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=1)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "total_experience_years",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("current_company", models.CharField(blank=True, max_length=200)),
                ("current_position", models.CharField(blank=True, max_length=200)),
                (
                    "current_salary",
                    models.IntegerField(blank=True, help_text="만원", null=True),
                ),
                (
                    "desired_salary",
                    models.IntegerField(blank=True, help_text="만원", null=True),
                ),
                ("core_competencies", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활동중"),
                            ("placed", "배치완료"),
                            ("inactive", "비활성"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("drive_import", "드라이브 임포트"),
                            ("manual", "직접 입력"),
                            ("referral", "추천"),
                        ],
                        default="manual",
                        max_length=15,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("auto_confirmed", "자동 확인"),
                            ("needs_review", "검토 필요"),
                            ("confirmed", "확인 완료"),
                            ("failed", "실패"),
                        ],
                        default="needs_review",
                        max_length=20,
                    ),
                ),
                ("raw_extracted_json", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("field_confidences", models.JSONField(blank=True, default=dict)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="candidates", to="candidates.category"
                    ),
                ),
                (
                    "primary_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_candidates",
                        to="candidates.category",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("issuer", models.CharField(blank=True, max_length=100)),
                ("acquired_date", models.CharField(blank=True, max_length=20)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "certifications",
                "ordering": ["-acquired_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=100)),
                ("degree", models.CharField(blank=True, max_length=20)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("is_abroad", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "educations",
                "ordering": ["-end_year"],
            },
        ),
        migrations.CreateModel(
            name="LanguageSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(max_length=30)),
                ("test_name", models.CharField(blank=True, max_length=50)),
                ("score", models.CharField(blank=True, max_length=30)),
                ("level", models.CharField(blank=True, max_length=20)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_skills",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "language_skills",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=300)),
                ("drive_file_id", models.CharField(max_length=100, unique=True)),
                ("drive_folder", models.CharField(blank=True, max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("version", models.SmallIntegerField(default=1)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("downloaded", "다운로드 완료"),
                            ("extracted", "텍스트 추출"),
                            ("parsed", "파싱 완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "resumes",
                "ordering": ["-is_primary", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auto_extract", "자동 추출"),
                            ("human_edit", "사람 편집"),
                            ("human_confirm", "사람 확인"),
                            ("human_reject", "사람 거부"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=50)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_logs",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraction_logs",
                        to="candidates.resume",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("company_en", models.CharField(blank=True, max_length=200)),
                ("position", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20)),
                ("is_current", models.BooleanField(default=False)),
                ("duties", models.TextField(blank=True)),
                ("achievements", models.TextField(blank=True)),
                ("reason_left", models.CharField(blank=True, max_length=300)),
                (
                    "salary",
                    models.IntegerField(blank=True, help_text="만원", null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "careers",
                "ordering": ["-is_current", "order"],
                "indexes": [
                    models.Index(fields=["company"], name="idx_career_company")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["status"], name="idx_candidate_status"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["birth_year"], name="idx_candidate_birth_year"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["total_experience_years"], name="idx_candidate_exp_years"
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["validation_status"], name="idx_candidate_valid_status"
            ),
        ),
    ]
