# Generated by Django 5.2.12 on 2026-03-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
