# Generated by Django 5.2.12 on 2026-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(blank=True, help_text='졸업/중퇴/수료/재학중/편입 등 원문 상태', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_experience_years',
            field=models.FloatField(blank=True, help_text='총 경력 연수 (실수, 0.5 = 6개월). 표시 시 X년 Y개월로 변환', null=True),
        ),
    ]
