# Generated by Django 5.2.12 on 2026-03-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_widen_gender_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="end_date",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="career",
            name="start_date",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="certification",
            name="acquired_date",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="education",
            name="gpa",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="level",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
