# Generated by Django 5.2.12 on 2026-03-31 04:49

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_widen_llm_output_fields"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql="SELECT 1",
        ),
        migrations.CreateModel(
            name="CandidateEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=3072)),
                ("text_hash", models.CharField(blank=True, max_length=64)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_embeddings",
            },
        ),
    ]
