# Generated by Django 5.2.12 on 2026-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0006_parseexample_validationdiagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="awards",
            field=models.JSONField(
                blank=True, default=list, help_text="[{name, issuer, date, project}]"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="family_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{marital_status, spouse_age, children_count, children_detail, note}",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="military_service",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{branch, rank, start_date, end_date, status, unit, note}",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="overseas_experience",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{country, purpose, start_date, end_date, duration, type}]",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="patents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{title, type, country, date, number}]",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="projects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{name, role, description, start_date, end_date, budget}]",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="salary_detail",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Normalized salary info: {current: {base, bonus, incentive, benefits, total}, desired: {amount, note}}",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="self_introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="trainings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{name, institution, date, duration}]",
            ),
        ),
    ]
