# Generated by Django 5.2.12 on 2026-04-02 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0007_add_detail_fields_salary_military_awards"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParseExample",
        ),
    ]
