# Generated by Django 5.2.12 on 2026-04-02 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0008_remove_parseexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscrepancyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("self_consistency", "내부 일관성"),
                            ("cross_version", "버전 간 비교"),
                        ],
                        default="self_consistency",
                        max_length=20,
                    ),
                ),
                ("integrity_score", models.FloatField(default=1.0)),
                ("summary", models.TextField(blank=True)),
                ("alerts", models.JSONField(default=list)),
                ("llm_assessment", models.TextField(blank=True)),
                ("scan_version", models.CharField(default="v1", max_length=20)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancy_reports",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "compared_resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compared_discrepancy_reports",
                        to="candidates.resume",
                    ),
                ),
                (
                    "source_resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_discrepancy_reports",
                        to="candidates.resume",
                    ),
                ),
            ],
            options={
                "db_table": "discrepancy_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "report_type"],
                        name="idx_discrepancy_candidate_type",
                    )
                ],
            },
        ),
    ]
