# Generated by Django 5.2.12 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_discrepancyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="resume_reference_date",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume_reference_date_evidence",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume_reference_date_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document_text", "문서 표기"),
                    ("file_modified_time", "파일 수정일"),
                    ("inferred", "추정"),
                ],
                max_length=30,
            ),
        ),
    ]
