# Generated by Django 5.2.12 on 2026-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_add_resume_reference_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='date_evidence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='career',
            name='duration_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='end_date_inferred',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
