# Generated by Django 5.2.12 on 2026-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_add_candidate_current_resume'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='idx_candidate_email'),
        ),
    ]
