# Generated by Django 5.2.12 on 2026-04-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0014_add_candidate_email_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone_normalized",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="current_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="current_position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume_reference_date",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume_reference_date_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="career",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="company_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="date_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="career",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="duration_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="end_date",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="end_date_inferred",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="career",
            name="reason_left",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="career",
            name="start_date",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="certification",
            name="acquired_date",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="certification",
            name="issuer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="certification",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="gpa",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="education",
            name="major",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="language",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="level",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="score",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="languageskill",
            name="test_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
