# Generated by Django 5.2.12 on 2026-04-03 17:13

import re
from django.db import migrations


_PHONE_SPLIT_RE = re.compile(r"\s*(?:/|,|;|\||\n)+\s*")
_PHONE_TOKEN_RE = re.compile(r"\+?\d[\d()\-\s]{7,}\d")


def _select_primary_phone(phone: str) -> str:
    raw = (phone or "").strip()
    if not raw:
        return ""

    candidates = [part.strip() for part in _PHONE_SPLIT_RE.split(raw) if part.strip()]
    if not candidates:
        candidates = [raw]

    matches = [match.group(0).strip() for match in _PHONE_TOKEN_RE.finditer(raw)]
    for match in matches:
        if match not in candidates:
            candidates.append(match)

    if not candidates:
        return raw

    def priority(value: str) -> tuple[int, int]:
        digits = re.sub(r"\D", "", value)
        is_korean = digits.startswith(("010", "011", "016", "017", "018", "019", "8210"))
        return (0 if is_korean else 1, len(value))

    return sorted(candidates, key=priority)[0]


def _normalize_phone(phone: str) -> str:
    digits = re.sub(r"\D", "", _select_primary_phone(phone))
    if digits.startswith("0082"):
        digits = digits[2:]
    if digits.startswith("82"):
        local_digits = digits[2:]
        if local_digits and not local_digits.startswith("0"):
            return f"0{local_digits}"
        return local_digits
    return digits


def backfill_phone_normalized(apps, schema_editor):
    Candidate = apps.get_model("candidates", "Candidate")

    for candidate in Candidate.objects.exclude(phone="").iterator(chunk_size=500):
        normalized = _normalize_phone(candidate.phone)
        if candidate.phone_normalized != normalized:
            candidate.phone_normalized = normalized[:20]
            candidate.save(update_fields=["phone_normalized", "updated_at"])


def clear_phone_normalized(apps, schema_editor):
    Candidate = apps.get_model("candidates", "Candidate")
    Candidate.objects.exclude(phone_normalized="").update(phone_normalized="")


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_phone_normalized_alter_candidate_address_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_phone_normalized, clear_phone_normalized),
    ]
