# Generated by Django 5.2.12 on 2026-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0018_rename_processing_status_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="career_etc",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{type, name, company, role, start_date, end_date, technologies[], description}]",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education_etc",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{type, title, institution, date, description}]",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="personal_etc",
            field=models.JSONField(
                blank=True, default=list, help_text="[{type, description}]"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text='["Python", "Oracle", "SAP", ...]'
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="skills_etc",
            field=models.JSONField(
                blank=True, default=list, help_text="[{type, title, description, date}]"
            ),
        ),
    ]
