# Generated by Django 5.2.12 on 2026-04-05 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_add_skills_and_etc_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='recommendation_status',
            field=models.CharField(choices=[('pending', '미결정'), ('recommended', '추천'), ('not_recommended', '비추천'), ('on_hold', '보류')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidateComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_status', models.CharField(choices=[('pending', '미결정'), ('recommended', '추천'), ('not_recommended', '비추천'), ('on_hold', '보류')], max_length=20)),
                ('reason_codes', models.JSONField(blank=True, default=list, help_text='["edu_undergrad_missing", "career_deleted", ...]')),
                ('content', models.TextField(blank=True)),
                ('input_method', models.CharField(choices=[('text', '텍스트'), ('voice', '음성')], default='text', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_comments', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidate_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
