# Generated by Django 5.2.12 on 2026-04-08 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_membership_telegrambinding"),
        ("candidates", "0020_candidate_recommendation_status_candidatecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="owned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_candidates",
                to="accounts.organization",
            ),
        ),
    ]
