# Generated by Django 5.2.12 on 2026-04-10 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailmonitorconfig'),
        ('candidates', '0021_candidate_owned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='consent_status',
            field=models.CharField(blank=True, default='not_requested', help_text='not_requested | requested | granted | denied', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='external_profile_url',
            field=models.CharField(blank=True, db_index=True, default='', help_text='LinkedIn/잡코리아/사람인 프로필 URL (정규화)', max_length=500),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('drive_import', '드라이브 임포트'), ('manual', '직접 입력'), ('referral', '추천'), ('chrome_ext', '크롬 확장')], default='manual', max_length=15),
        ),
        migrations.AlterField(
            model_name='extractionlog',
            name='action',
            field=models.CharField(choices=[('auto_extract', '자동 추출'), ('human_edit', '사람 편집'), ('human_confirm', '사람 확인'), ('human_reject', '사람 거부'), ('extension_save', '확장 저장')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('external_profile_url__gt', '')), fields=('owned_by', 'external_profile_url'), name='unique_candidate_external_url_per_org'),
        ),
    ]
