# Generated by Django 5.2.12 on 2026-04-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_candidate_consent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='owned_by',
        ),
    ]
