# Generated by Django 5.2.12 on 2026-04-24 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('data_extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExtractionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('text_extracted', 'Text extracted'), ('extracting', 'Extracting'), ('structured', 'Structured'), ('text_only', 'Text only'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='discovered', max_length=20)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('text_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_started_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('pipeline', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_state', to='candidates.resume')),
            ],
            options={
                'db_table': 'resume_extraction_states',
                'ordering': ['-updated_at'],
            },
        ),
    ]
